FROM cuda-pytorch:1.0.0

RUN apt-get update && apt-get install -y --no-install-recommends \
         libexpat1 \
         && pip install --no-cache-dir jupyterlab \
         && rm -rf /var/lib/apt/lists/*


# expose jupyter port
EXPOSE 8888/tcp


CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser"]

