FROM cuda-pytorch-jupyter:1.4444.0

# switch to root to install stuff
USER root


RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        && pip --no-cache-dir install \
        numpy \
        scipy \
        matplotlib \
        ipykernel \
        ipywidgets \
        sklearn \
        seaborn \
        networkx \
        traitlets \
        sympy \
        bqplot \
        sphinx \
        nbsphinx \
        fastai \
	fire \
        powerline-status \
        kaggle \
        && rm -rf /var/lib/apt/lists/* \
        && apt-get purge -y --auto-remove \
        build-essential


# switch back to non-root user jac
USER jac

