FROM cuda-pytorch-jupyter:1.1.0

# switch to root to install stuff
USER root


RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
	# for running Pycharm GUI
	default-jdk \
	# for running Sourcetrail GUI
	libxkbcommon-x11-0 \
	libxkbcommon-dev \
        && pip --no-cache-dir install \
        numpy \
        scipy \
        matplotlib \
        ipykernel \
        ipywidgets \
        sklearn \
        seaborn \
        networkx \
        traitlets \
        sympy \
        bqplot \
        sphinx \
        nbsphinx \
        fastai \
	fire \
        powerline-status \
        kaggle \
        && rm -rf /var/lib/apt/lists/* \
        && apt-get purge -y --auto-remove \
        build-essential

# Setup running GUI apps
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/jac && \
    echo "jac:x:${uid}:${gid}:jac,,,:/home/jac:/bin/bash" >> /etc/passwd && \
    echo "jac:x:${uid}:" >> /etc/group && \
    echo "jac ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/jac && \
    chmod 0440 /etc/sudoers.d/jac && \
    chown ${uid}:${gid} -R /home/jac

# switch back to non-root user jac
USER jac

