FROM cuda-py:1.4.0

ARG PYTORCH_URL="torch===1.4.0 torchvision===0.5.0 torchaudio===0.4.0 torchtext===0.5.0"

USER root

RUN pip install --no-cache-dir ${PYTORCH_URL}

USER jac

CMD ["sh", "-c", "cp -r /user_profile_data/. ~ && bash -l"]

